insert into product_category (id, description, name) values (1, 'Venereal disease NEC', 'Laptops');
insert into product_category (id, description, name) values (2, 'Disloc metacarpophaln-cl', 'Accessories');
insert into product_category (id, description, name) values (3, 'Simple microphthalmos', 'Flat Screen Monitors');
insert into product_category (id, description, name) values (4, 'Carbuncle of trunk', 'Printers');
insert into product_category (id, description, name) values (5, 'Dislocation jaw-closed', 'Multifunction Printers');
insert into product_category (id, description, name) values (6, 'Soft tissue disorder NEC', 'Mice');
insert into product_category (id, description, name) values (7, 'Open wound of palate', 'Keyboards');
insert into product_category (id, description, name) values (8, 'Inf mcrg rstn oth drg ml', 'Mousepads');
insert into product_category (id, description, name) values (9, 'Abn ftl hrt rate/rhy-uns', 'Computer System Accessories');
insert into product_category (id, description, name) values (10, 'Opn brain lac-brief coma', 'Graphic Cards');
insert into product_category (id, description, name) values (11, 'Opn brain lac-brief coma', 'Scanners');
insert into product_category (id, description, name) values (12, 'Opn brain lac-brief coma', 'Speakers');
insert into product_category (id, description, name) values (13, 'Opn brain lac-brief coma', 'Software');